---
title: "Islam Certificate of Peace Hoax atau Fakta"
description: |
  Debunking hoax
author:
  - name: Aldilas Achmad Nursetyo
    url: https://aldeetropolis.github.io/about.html
date: 03-09-2016
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Baru-baru ini saya dikejutkan oleh sharing di media sosial bahwa UNESCO telah menerbitkan sebuah sertifikat kedamaian untuk agama Islam. Sertifikat tersebut bahkan diterbitkan dan dibagikan ke sejumlah pusat Islam (Islamic center) di US untuk ditempel di masjidnya sehingga dapat menentramkan penganut agama Islam di tempatnya. Demikian dikutip oleh website [Junta Ka Reporter](http://www.juntakareporter.com/world/unesco-declares-islam-as-the-most-peaceful-religion-of-the-world/) pada tanggal 4 Juli 2016.

Jujur saja, _I smell something fishy about this news_. Kecurigaan __pertama__ adalah saya tidak pernah mendengar UNESCO mengeluarkan sertifikat apapun mengenai tingkat kedamaian suatu entitas, entah itu agama, negara, organisasi, apapun itu. Memang UNESCO membidangi salah satunya adalah tentang perdamaian. Tetapi berkali-kali saya bongkar website resmi UNESCO tidak ada yang namanya sertifikasi atau penghargaan tersebut.

__Kedua__, kita perlu tahu apa dan siapa yang menulis berita tersebut untuk pertama kalinya. Hingga hari ini (9 Juli 2016) laman berita ini sudah dishare atau lebih tepatnya copy-paste oleh beberapa website yang mencurigakan juga. Tetapi saya yakin kalau website ini adalah website penyedia berita-berita parodi dan satir seperti [The Onion](http://www.theonion.com). Bukti pertama adalah ada website lain dengan nama mirip yaitu [Janta Ka Reporter](http://www.jantakareporter.com) yang merupakan salah satu media berita kenamaan di India. Penulis Junta Ka Reporter juga [mengklaim](https://www.facebook.com/notes/junta-ka-reporter/important-and-factual-for-a-change-update/1696460917260164) bahwa website ini merupakan website yang berisi berita satir dan parodi.

Bukti kedua, agak aneh ketika saya buka laman [Contact Us](http://www.juntakareporter.com/contact-us/) yang menunjukkan sebuah Google Map yang menunjuk ke alamat _Institute of Mental Health_ di India. Yang mana saya yakin hanya orang yang bercanda yang memberikan alamat rumah sakit jiwa di laman kontaknya.

__Ketiga__, saya coba analisis mengenai tanda tangan [Irina Bokova](https://en.wikipedia.org/wiki/Irina_Bokova) (Director-General UNESCO) pada sertifikat tersebut. Saya percaya, tidak ada satu orang pun yang mampu membuat dua tanda tangan yang sama persis. Namun, yang saya temukan, tanda tangan Irina Bokova pada sertifikat tersebut sama persis dengan tanda tangannya pada sertifikat inskripsi pernyataan karya Karl Marx sebagai kenang-kenangan dunia internasional (_Memory of The World_).

__Keempat__, saya coba cari mengenai [International Peace Foundation](http://www.peace-foundation.net/). Organisasi ini benar adanya, bukan hoax internet. Tapi setelah saya buka laman _press release_ tidak disebutkan kalau mereka baru saja mengeluarkan sertifikat tersebut.

Hingga saat ini belum ada klaim atau klarifikasi baik dari UNESCO maupun _International Peace Foundation_ mengenai kebenaran berita ini. Namun, dari analisis saya di atas saya harap sudah menjelaskan kesimpulan apa yang akan ditarik mengenai kebenaran berita ini: HOAX ataukah FAKTA?!

### Kesimpulan

Artikel ini bertujuan untuk menunjukkan suatu kebohongan di dunia maya. Saya seorang muslim, siapa yang tidak bersuka cita kalau Islam terbukti sebagai agama perdamaian melalui serangkain studi ilmiah. Namun, dusta tetaplah dusta. Tidak ada kesenangan yang diperoleh dengan menyebarkan dusta. Maka saya berkesimpulan bahwa berita ini merupakan suatu HOAX internet yang saya tidak tahu tujuannya apa. _Keep sharing keep posting, but think before sharing/posting_ ya.

Ciao.
